bq_new:
  outputs:
    dev:
      dataset: dev_dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west3
      method: oauth
      priority: interactive
      project: new-ads-bigquery-data
      threads: 4
      type: bigquery
    
    run_git:
      dataset: dev_dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west3
      method: service-account-json
      priority: interactive
      project: new-ads-bigquery-data
      threads: 4
      type: bigquery
      
      # These fields come from the service account json keyfile
      keyfile_json:
        type: service_account
        project_id: new-ads-bigquery-data
        private_key_id: "{{ env_var('DBT_ENV_SECRET_BQ_PRKEY_ID') }}"
        private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCdTJsovqbZZMAm\n4emVWVBHQqAWlUQqtv+ZwFRHKyzD3HRnjfAU8nS7rq085cWRGfHjAQibZy834HaV\naQsarw+kMxvt5Ag1H7aEpeo8QOSMH9vNd800b4jUswH8alWBh+p+Cv0QwEMsJAwp\n0Ba/SPpIqoEZpWwe8mJVI9fAQNt3INCKMYE7Sbb9blfWu+XSDSbY/dhEfw7rKi7i\n0OF8NdfjnBXu/Fe4ssaW4GB0PicfqiadYRmlcFhghu1L5aF6/yFIwNhh3xdrm/Lu\nx/v/jcImbtzj70bhu8MqzppMgTnqtbCM5Y2S3w401jKkdBKlhMRYptqAHV3UeilS\njwtGSzh1AgMBAAECggEAJnqPpyEyQBJPFgPkB8qMIo54CmYzwW44KwSbKTi0z+nN\nGOrmDL291A6YJsI/eO4bl5AQarGMYbMZVxXV505lOWHeRmymnFY4aA0NNnWaYvPF\nKWdRza6uDngGt5hMd+4HbRNjkhYyKGleB1l1ww/HWADLqXonr49UAidNNyS2exar\nkCzv1+DYjOVpXlub97Eb9/x5LYHUUK0cDgQVsut9fu8XzD6YRRPeTCgMTPUgN+i9\nNxfGSw2MbaCTh5P62ZHMz9Pc0vU9NlXdUo4qe6SUyQRIFPFXXj1UuwRGPGqvT2UA\nxuSslp7aCLEEJe+RP7IdPgXBYxHJOrHNY6MYiWvBsQKBgQDbsjnV3JmkwZWrS6N4\n71/Qd+GveFg49oECdMpYVJFCmSqXblVrVecuyrTzkT6Fr++cbZs3OSt3flbwSnLS\nj64L46DdwCH3bdZpvGkIDIpclaFudI4c7AOd21aozIJwcC4t/MASvr/VZaAovGzN\nWSAMMKAF+MgCfvVrFMDF+nVS0QKBgQC3Ss/Co38HmVhvrQIrFU2sNR5DunRnmT5S\nZ4g9K2iNOFNsD85B0VBS1YBnx9+hnI1qVBnfIt6Gnq5sQy2J9IxKv0JfUqaUOC63\neGBNOBxyu+NNasEDQmRZN8V/VubuRLL7IzD/SwPWeMw6K93INd5KhhJ04Zl7Fl0E\nQWYbSpPMZQKBgQCa3R5Br5gqeD89mTrpg6tBs0/GNgnSVYkJJzR/YVVn4boRNrhF\nyi8FX+SAEPFGoYdA+E5Cdi06tTcpeQFJhfiE7vc1eTs4RBexPxu2jch2jQ9XYhfP\nMVs3SibjJA4KnjkfN5xZWla1YUatkG0Nr3aUwS38J6stfzsWOXHN3MgZEQKBgHxF\nmstqsqviSlWdRYUUco85jIV7G4VKHzkbvQFMNxzYfaccqElzszQWUXMLzxHx5Oec\nkdX5/EnluHjqqyuHxL7BIi0jCpIf7Xyzfweb7Z3Uye4pXSfqkcLzz1HhB72wknE3\nkPbmU3nMeRtPtpUSAN8iO81HUBpmNTa3aJVEYSUJAoGBAIUTwVngZooFsLyMkdFU\n/jYCxeMiKZ0XDkyAWfHC9GO5Tq8adam1kwZ5rzWBZjOUKXmE4mhI6txGaFuAoCto\nVYp5CzvhXtk8cQ2HMbLeZ1e6KK34M5ZvyGENa/n2nxGXgkvWaCujhL9NV98Ji268\nyS0Xp9dEw+NqFEhl4OTKbZik\n-----END PRIVATE KEY-----\n" #"{{ env_var('DBT_ENV_SECRET_BQ_PRKEY') }}"
        client_email: "{{ env_var('DBT_ENV_SECRET_BQ_CLIENT_MAIL') }}"
        client_id: "{{ env_var('DBT_ENV_SECRET_BQ_CLIENT_ID') }}"
        auth_uri: https://accounts.google.com/o/oauth2/auth
        token_uri: https://oauth2.googleapis.com/token
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        client_x509_cert_url: "{{ env_var('DBT_ENV_SECRET_BQ_CLIENT_CERT_URL') }}"

  target: dev