
version: 2

models:
#Google Ads
  - name: stg_google_ads_campaign_stats
    description: '{{ doc("campaign_stats") }}'
    columns:
      - name: _fivetran_id
        description: '{{ doc("fivetran") }}'
      - name: _fivetran_synced
        description: '{{ doc("fivetran") }}'
      - name: customer_id
        description: '{{ doc("ad_account") }}'
      - name: active_view_impressions
        description: '{{ doc("unused_columns") }}'
      - name: active_view_measurability
        description: '{{ doc("unused_columns") }}'
      - name: active_view_measurable_cost_micros
        description: '{{ doc("unused_columns") }}'
      - name: active_view_measurable_impressions
        description: '{{ doc("unused_columns") }}'
      - name: active_view_viewability
        description: '{{ doc("unused_columns") }}'
      - name: ad_network_type
        description: '{{ doc("unused_columns") }}'
      - name: base_campaign
        description: '{{ doc("unused_columns") }}'
      - name: clicks
        description: '{{ doc("clicks") }}'
      - name: conversions
        description: >
          Conversions gemäß Google Ads - sollte nicht verwendet werden. 
          Für Reportings werden Werte direkt aus Google Analytics genutzt.   
      - name: conversions_value
        description: '{{ doc("unused_columns") }}'
      - name: cost
        description: '{{ doc("cost") }}'
      - name: device
        description: '{{ doc("device") }}'
      - name: id
        description: Kampagnen-ID Google, wichtigster Sekundärschlüssel
        tests:
          - not_null
      - name: impressions
        description: '{{ doc("impressions") }}'
      - name: interaction_event_types
        description: '{{ doc("unused_columns") }}'
      - name: interactions
        description: '{{ doc("unused_columns") }}'
      - name: view_through_conversions
        description: '{{ doc("unused_columns") }}'
      - name: active_view_viewability
        description: '{{ doc("unused_columns") }}'
      - name: active_view_viewability
        description: '{{ doc("unused_columns") }}'
      
  - name: stg_google_ads_campaign_history
    description: '{{ doc("campaign_history") }}'
    columns:
      - name: _fivetran_start
        description: '{{ doc("fivetran") }}'
      - name: id
        description: Kampagnen-ID Google, wichtigster Sekundärschlüssel
        tests:
          - not_null
      - name: _fivetran_active
        description: '{{ doc("fivetran") }}'
      - name: _fivetran_end
        description: '{{ doc("fivetran") }}'
      - name: _fivetran_synced
        description: '{{ doc("fivetran") }}'
      - name: ad_serving_optimization_status
        description: '{{ doc("unused_columns") }}'
      - name: advertising_channel_subtype
        description: '{{ doc("unused_columns") }}'
      - name: advertising_channel_type
        description: '{{ doc("unused_columns") }}'
      - name: base_campaign_id
        description: '{{ doc("unused_columns") }}'
      - name: customer_id
        description: '{{ doc("ad_account") }}'
      - name: end_date
        description: '{{ doc("unused_columns") }}'
      - name: experiment_type
        description: '{{ doc("unused_columns") }}'
      - name: final_url_suffix
        description: '{{ doc("unused_columns") }}'
      - name: frequency_caps
        description: '{{ doc("unused_columns") }}'
      - name: campaign
        description: '{{ doc("campaign_name") }}'
      - name: optimization_score
        description: '{{ doc("unused_columns") }}'
      - name: payment_mode
        description: '{{ doc("unused_columns") }}'
      - name: serving_status
        description: '{{ doc("unused_columns") }}'
      - name: start_date
        description: '{{ doc("unused_columns") }}'
      - name: status
        description: '{{ doc("unused_columns") }}'
      - name: tracking_url_template
        description: '{{ doc("unused_columns") }}'
      - name: updated_at
        description: '{{ doc("unused_columns") }}'
      - name: vanity_pharma_display_url_mode
        description: '{{ doc("unused_columns") }}'
      - name: vanity_pharma_text
        description: '{{ doc("unused_columns") }}'
      - name: video_brand_safety_suitability
        description: '{{ doc("unused_columns") }}'
      - name: Source
        description: '{{ doc("source_medium_manual") }}'
      - name: Medium
        description: '{{ doc("source_medium_manual") }}'
      - name: Partner
        description: '{{ doc("Partner") }}'
        test:
          - not_null
      - name: CampaignID
        description: '{{ doc("campaignID") }}'
        test:
          - not_null

#Bing Ads
  - name: stg_bing_ads_campaign_history
    description: '{{ doc("campaign_history") }}'
    columns:
      - name: id
        description: Kampagnen-ID Microsoft, wichtigster Sekundärschlüssel
        tests:
          - not_null
      - name: Partner
        description: '{{ doc("Partner") }}'
        test:
          - not_null
      - name: CampaignID
        description: '{{ doc("campaignID") }}'
        test:
          - not_null

#Google Analytics
  - name: stg_google_analytics_314060132
    description: >
      Enthält alle GA4-Events in Tabellenform ohne Schachtelung. 
      Bereinigt fehlerhafte Events ohne Session-ID. 
      Offzielle Doku Google: https://support.google.com/analytics/answer/7029846?hl=en#zippy=
    columns:
      - name: ltv_revenue
        description: User Lifetime Value
      - name: ltv_currency
        description: Einheit des User Lifetime Value

  - name: stg_google_analytics_345727078
    description: >
      Enthält alle GA4-Events in Tabellenform ohne Schachtelung. 
      Bereinigt fehlerhafte Events ohne Session-ID. 
      Offzielle Doku Google: https://support.google.com/analytics/answer/7029846?hl=en#zippy=
    columns:
      - name: ltv_revenue
        description: User Lifetime Value
      - name: ltv_currency
        description: Einheit des User Lifetime Value

  - name: stg_google_analytics_historic_campaigns_new
    description: Enthält alle historischen Kampagnen aus Universal Analytics / GA3
    columns:
      - name: Campaign
        description: '{{ doc("campaign_name") }}'
      - name: Partner
        description: '{{ doc("Partner") }}'
      - name: Source
        description: '{{ doc("source_medium_manual") }}'
      - name: Medium
        description: '{{ doc("source_medium_manual") }}'
      - name: CampaignID
        description: '{{ doc("campaignID") }}'

  - name: stg_google_analytics_historic_campaigns_ke
    description: Enthält alle historischen Kampagnen aus Universal Analytics / GA3
    columns:
      - name: Campaign
        description: '{{ doc("campaign_name") }}'
      - name: Partner
        description: '{{ doc("Partner") }}'
      - name: Source
        description: '{{ doc("source_medium_manual") }}'
      - name: Medium
        description: '{{ doc("source_medium_manual") }}'
      - name: CampaignID
        description: '{{ doc("campaignID") }}'

  - name: stg_google_analytics_historic_transactions_new
    description: Enthält alle historischen Transaktionen aus Universal Analytics / GA3
    columns:
      - name: Date
        description: Datum der Transaktionen je Kampagne.
      - name: Campaign
        description: '{{ doc("campaign_name") }}'
      - name: Medium
        description: '{{ doc("source_medium_manual") }}'
      - name: Source
        description: '{{ doc("source_medium_manual") }}'
      - name: ProductCategory
        description: '{{ doc("productcategory") }}'
      - name: Transactions
        description: '{{ doc("transactions") }}'
      - name: Keyword
        description: '{{ doc("keyword") }}'
      - name: KeywordMatchType
        description: '{{ doc("KeywordMatchType") }}'
      - name: Partner
        description: '{{ doc("Partner") }}'
      - name: CampaignID
        description: '{{ doc("campaignID") }}'

  - name: stg_google_analytics_historic_transactions_ke
    description: Enthält alle historischen Transaktionen aus Universal Analytics / GA3
    columns:
      - name: Date
        description: Datum der Transaktionen je Kampagne.
      - name: Campaign
        description: '{{ doc("campaign_name") }}'
      - name: Medium
        description: '{{ doc("source_medium_manual") }}'
      - name: Source
        description: '{{ doc("source_medium_manual") }}'
      - name: ProductCategory
        description: '{{ doc("productcategory") }}'
      - name: Transactions
        description: '{{ doc("transactions") }}'
      - name: Keyword
        description: '{{ doc("keyword") }}'
      - name: KeywordMatchType
        description: '{{ doc("KeywordMatchType") }}'
      - name: Partner
        description: '{{ doc("Partner") }}'
      - name: CampaignID
        description: '{{ doc("campaignID") }}'

  - name: stg_google_analytics_historic_goal_conversions_new
    description: Enthält alle historischen Zielvorhaben-Conversions aus Universal Analytics / GA3
    columns:
      - name: Date
        description: Datum der Conversion je Kampagne.
      - name: Campaign
        description: '{{ doc("campaign_name") }}'
      - name: Medium
        description: '{{ doc("source_medium_manual") }}'
      - name: Source
        description: '{{ doc("source_medium_manual") }}'
      - name: Keyword
        description: '{{ doc("keyword") }}'
      - name: KeywordMatchType
        description: '{{ doc("KeywordMatchType") }}'
      - name: NameZielvorhaben
        description: '{{ doc("namezielvorhaben") }}'
      - name: Conversions
        description: '{{ doc("conversions") }}'  
      - name: Partner
        description: '{{ doc("Partner") }}'
      - name: CampaignID
        description: '{{ doc("campaignID") }}'

  - name: stg_google_analytics_historic_goal_conversions_newwae
    description: Enthält alle historischen Zielvorhaben-Conversions aus Universal Analytics / GA3
    columns:
      - name: Date
        description: Datum der Conversion je Kampagne.
      - name: Campaign
        description: '{{ doc("campaign_name") }}'
      - name: Medium
        description: '{{ doc("source_medium_manual") }}'
      - name: Source
        description: '{{ doc("source_medium_manual") }}'
      - name: Keyword
        description: '{{ doc("keyword") }}'
      - name: KeywordMatchType
        description: '{{ doc("KeywordMatchType") }}'
      - name: NameZielvorhaben
        description: '{{ doc("namezielvorhaben") }}'
      - name: Conversions
        description: '{{ doc("conversions") }}'  
      - name: Partner
        description: '{{ doc("Partner") }}'
      - name: CampaignID
        description: '{{ doc("campaignID") }}'